# Generated by Django 4.2.19 on 2025-02-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Headmaster', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Headmaster', models.TextField()),
                ('Cabinet', models.TextField()),
                ('Number_phone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.TextField()),
                ('Headman', models.TextField()),
                ('Specialty', models.TextField()),
                ('Faculty', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.TextField()),
                ('Age', models.IntegerField()),
                ('Course', models.IntegerField()),
                ('Specialty', models.TextField()),
                ('Number_phone', models.TextField()),
                ('Faculty', models.TextField()),
                ('Gender', models.TextField()),
                ('Group', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.TextField()),
                ('Age', models.IntegerField()),
                ('Specialty', models.TextField()),
                ('Number_phone', models.TextField()),
                ('Faculty', models.TextField()),
                ('Gender', models.TextField()),
            ],
        ),
    ]
