# Generated by Django 4.2.19 on 2025-02-25 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Headmaster', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Headmaster', models.TextField()),
                ('Cabinet', models.TextField()),
                ('Number_phone', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.TextField()),
                ('Headman', models.TextField()),
                ('Faculty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Years', models.IntegerField(default=4)),
                ('Faculty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.TextField()),
                ('Age', models.IntegerField()),
                ('Number_phone', models.TextField()),
                ('Gender', models.TextField()),
                ('Subject', models.TextField(default=None)),
                ('Faculty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.faculty')),
                ('Specialty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.specialty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.TextField()),
                ('Date_of_birth', models.DateField(null=True)),
                ('Course', models.IntegerField()),
                ('Number_phone', models.TextField()),
                ('Gender', models.TextField()),
                ('Faculty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.faculty')),
                ('Group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.group')),
                ('Specialty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.specialty')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='Specialty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.specialty'),
        ),
    ]
