# Generated by Django 4.2.19 on 2025-02-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Age',
        ),
        migrations.AddField(
            model_name='student',
            name='Date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
