# Generated by Django 4.2.19 on 2025-02-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_age_student_date_of_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teachers',
            new_name='Teacher',
        ),
    ]
